//  DEFAULT Settings
export const ASIDE = "ASIDE";
export const SIDEBAR = "SIDEBAR";
export const DARK = "DARK";

// DEFAULT Authorization
export const LOGIN = "LOGIN";

// DEFAULT Message Handler
export const MESSAGE = "MESSAGE";
export const ERROR_MESSAGE = "Internal server error! Please try again later";
/**
 *  Items
 **/
// Items List
export const REDIRECT_BACK_ITEMS = "REDIRECT_BACK_ITEMS";
export const GET_ITEM_LIST = "GET_ITEM_LIST";
export const GET_ITEM_STOCK = "GET_ITEM_STOCK";
export const GET_ITEM_STORES = "GET_ITEM_STORES";
export const ITEM_SAVE = "ITEM_SAVE";
export const TOGGLE_ITEM_DELETE_SELECT = "TOGGLE_ITEM_DELETE_SELECT";
export const TOGGLE_ALL_ITEM_DELETE_SELECT = "TOGGLE_ALL_ITEM_DELETE_SELECT";
export const DELETE_ITEM_LIST = "DELETE_ITEM_LIST";
export const TOGGLE_SELECT_ALL_ITEM_STORES = "TOGGLE_SELECT_ALL_ITEM_STORES";
export const TOGGLE_SELECT_SINGLE_ITEM_STORES =
  "TOGGLE_SELECT_SINGLE_ITEM_STORES";
export const SET_ITEM_STORE_PRICE = "SET_ITEM_STORE_PRICE";
export const SAVE_ITEM_VARIANTS = "SAVE_ITEM_VARIANTS";
export const UPDATE_VARIANT_PRICE = "UPDATE_VARIANT_PRICE";
export const UPDATE_VARIANT_COST = "UPDATE_VARIANT_COST";
export const UPDATE_VARIANT_SKU = "UPDATE_VARIANT_SKU";
export const UPDATE_VARIANT_BARCODE = "UPDATE_VARIANT_BARCODE";
export const DELETE_ITEM_VARIANTS_OPTION = "DELETE_ITEM_VARIANTS_OPTION";
export const DELETE_ITEM_VARIANTS = "DELETE_ITEM_VARIANTS";
// X Category list
export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST";
export const ADD_NEW_CATEGORY = "ADD_NEW_CATEGORY";
export const SELECT_ROW_ITEMS_CATEGORY = "SELECT_ROW_ITEMS_CATEGORY";
export const REDIRECT_BACK_CATEGORY = "REDIRECT_BACK_CATEGORY";
export const UPDATE_ITEM_CATEGORY = "UPDATE_ITEM_CATEGORY";
export const TOGGLE_CATEGORY_DELETE_SELECT = "TOGGLE_CATEGORY_DELETE_SELECT";
export const TOGGLE_ALL_CATEGORY_DELETE_SELECT =
  "TOGGLE_ALL_CATEGORY_DELETE_SELECT";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const TOGGLE_ITEM_STOCK = "TOGGLE_ITEM_STOCK";
export const SET_ITEM_STORE_IN_STOCK = "SET_ITEM_STORE_IN_STOCK";
export const SET_ITEM_STORE_LOW_STOCK = "SET_ITEM_STORE_LOW_STOCK";
// Discount List
export const GET_DISCOUNT_LIST = "GET_DISCOUNT_LIST";
export const ADD_NEW_DISCOUNT = "ADD_NEW_DISCOUNT";
export const UPDATE_ITEM_DISCOUNT = "UPDATE_ITEM_DISCOUNT";
export const REDIRECT_BACK_DISCOUNT = "REDIRECT_BACK_DISCOUNT";
export const SELECT_ROW_ITEMS_DISCOUNT = "SELECT_ROW_ITEMS_DISCOUNT";
export const TOGGLE_DISCOUNT_DELETE_SELECT = "TOGGLE_DISCOUNT_DELETE_SELECT";
export const TOGGLE_ALL_DISCOUNT_DELETE_SELECT =
  "TOGGLE_ALL_DISCOUNT_DELETE_SELECT";
export const DELETE_DISCOUNT = "DELETE_DISCOUNT";
export const UPDATE_ITEM_ROW_DATA = "UPDATE_ITEM_ROW_DATA";
export const REMOVE_ROW_DATA = "REMOVE_ROW_DATA";
//  Modifires
export const GET_MODIFIRES_LIST = "GET_MODIFIRES_LIST";
export const DELETE_MODIFIRES = "DELETE_MODIFIRES";
export const TOGGLE_ALL_MODIFIRES_DELETE_SELECT =
  "TOGGLE_ALL_MODIFIRES_DELETE_SELECT";
export const TOGGLE_MODIFIRES_DELETE_SELECT = "TOGGLE_MODIFIRES_DELETE_SELECT";
export const ADD_NEW_MODIFIER = "ADD_NEW_MODIFIER";
export const REDIRECT_BACK_MODIFIER = "REDIRECT_BACK_MODIFIER";
export const UPDATE_MODIFIER_ROW_DATA = "UPDATE_MODIFIER_ROW_DATA";
export const UPDATE_MODIFER = "UPDATE_MODIFER";
export const UPDATE_ITEM_RECORD = "UPDATE_ITEM_RECORD";
/**
 *  Items End
 *Start Customers
 **/
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const ADD_NEW_CUSTOMER = "ADD_NEW_CUSTOMER";
export const REDIRECT_BACK_CUSTOMER = "REDIRECT_BACK_CUSTOMER";
export const TOGGLE_CUSTOMER_SINGLE_SELECT = "TOGGLE_CUSTOMER_SINGLE_SELECT";
export const TOGGLE_CUSTOMER_ALL_SELECT = "TOGGLE_CUSTOMER_ALL_SELECT";
export const DELETE_CUSTOMERS = "DELETE_CUSTOMERS";
export const ROW_DATA_CUSTOMER = "ROW_DATA_CUSTOMER";

/**
 *  Pos & Stores
 ****/
// stores
export const GET_STORES = "GET_STORES";
export const ADD_NEW_STORE = "ADD_NEW_STORE";
export const REDIRECT_BACK_STORE = "REDIRECT_BACK_STORE";
export const UPDATE_STORE_ROW_DATA = "UPDATE_STORE_ROW_DATA";
export const UPDATE_STORE_REDIRECT_STATES = "UPDATE_STORE_REDIRECT_STATES";
export const UPDATE_STORE = "UPDATE_STORE";
export const DELETE_STORE = "DELETE_STORE";

//  Pos Device Action
export const GET_POS_DEVICES = "GET_POS_DEVICES";
export const ADD_NEW_POS_DEVICE = "ADD_NEW_POS_DEVICE";
export const TOGGLE_POS_SINGLE_SELECT = "TOGGLE_POS_SINGLE_SELECT";
export const TOGGLE_POS_ALL_SELECT = "TOGGLE_POS_ALL_SELECT";
export const DELETE_POS_DEVICES = "DELETE_POS_DEVICES";
export const REDIRECT_BACK_POS_DEVICES = "REDIRECT_BACK_POS_DEVICES";
export const SELECT_ROW_DATA_UPDATE = "SELECT_ROW_DATA_UPDATE";
export const UPDATE_POS_DEVICE = "UPDATE_POS_DEVICE";
export const UPDATE_POS_DEIVCES_REDIRECT_STATES =
  "UPDATE_POS_DEIVCES_REDIRECT_STATES";
/**
 *  Pos & Stores End
 ****/
/**
 *  Dining Option
 ****/
export const GET_DINING_OPTION = "GET_DINING_OPTION";
export const ADD_NEW_DINING_OPTION = "ADD_NEW_DINING_OPTION";
export const REDIRECT_BACK_DINING = "REDIRECT_BACK_DINING";
export const UPDATE_ROW_DATA_DINING_OPTION = "UPDATE_ROW_DATA_DINING_OPTION";
export const UPDATE_DINING_OPTION = "UPDATE_DINING_OPTION";
export const DELETE_DINING_OPTION = "DELETE_DINING_OPTION";
/**
 *  Dining Option End
 ****/
/**
 *  Taxes
 ****/
export const TOGGLE_DININGS = "TOGGLE_DININGS";
export const TOGGLE_CATEGORY = "TOGGLE_CATEGORY";
export const GET_CATEGORY_ITEMS = "GET_CATEGORY_ITEMS";
export const TOGGLE_CATEGORY_ITEMS = "TOGGLE_CATEGORY_ITEMS";
export const GET_CATEGORY_TAX = "GET_CATEGORY_TAX";
export const GET_DINING_TAX = "GET_DINING_TAX";
export const DINING_SELECT_STATUS = "DINING_SELECT_STATUS";
export const CATEGORY_SELECT_STATUS = "CATEGORY_SELECT_STATUS";
export const CATEGORY_ITEMS_SELECT_STATUS = "CATEGORY_ITEMS_SELECT_STATUS";
export const GET_TAXES_TYPE = "GET_TAXES_TYPE";
export const GET_TAXES_OPTION = "GET_TAXES_OPTION";
export const GET_ITEM_TAXES = "GET_ITEM_TAXES";
export const TOGGLE_TAXES_SELECT_SINGLE = "TOGGLE_TAXES_SELECT_SINGLE";
export const TOGGLE_TAXES_SELECT_ALL = "TOGGLE_TAXES_SELECT_ALL";
export const INSERT_NEW_TAX = "INSERT_NEW_TAX";
export const DELETE_ITEM_TAXES = "DELETE_ITEM_TAXES";
export const REDIRECT_BACK_TAXES = "REDIRECT_BACK_TAXES";
export const UPDATE_ROW_DATA_TAX = "UPDATE_ROW_DATA_TAX";
export const UPDATE_ITEM_TAX = "UPDATE_ITEM_TAX";
export const REMOVE_UPDATE_ROW_DATA = "REMOVE_UPDATE_ROW_DATA";
/**
 *  Taxes  End
 *    Start Kitchen Printer
 ****/
export const GET_KICTCH_PRINTER = "GET_KICTCH_PRINTER";
export const ADD_NEW_KITCHEN_PRINTER = "ADD_NEW_KITCHEN_PRINTER";
export const DELETE_KITCHEN_PRINTER = "DELETE_KITCHEN_PRINTER";
export const TOGGLE_KITCHEN_PRINTER_SINGLE_SELECT =
  "TOGGLE_KITCHEN_PRINTER_SINGLE_SELECT";
export const TOGGLE_KITCHEN_PRINTER_SELECT_ALL =
  "TOGGLE_KITCHEN_PRINTER_SELECT_ALL";
export const REDIRECT_BACK_KITCHEN = "REDIRECT_BACK_KITCHEN";
export const SELECT_UPDATE_ROW = "SELECT_UPDATE_ROW";
export const UPDATE_KICTCH_PRINTER = "UPDATE_KICTCH_PRINTER";
export const UPDATE_KITCHEN_PRINTER_REDIRECT_STATES =
  "UPDATE_KITCHEN_PRINTER_REDIRECT_STATES";
/**
 *  End Kitchen Printer
 ****/
/**
 *  End Open Ticket
 ****/
export const ADD_NEW_OPEN_TICKET = "ADD_NEW_OPEN_TICKET";
export const REDIRECT_BACK_TICKET = "REDIRECT_BACK_TICKET";
export const GET_STORE_OPEN_TICKET = "GET_STORE_OPEN_TICKET";
/**
 *  End Open Ticket
 *  Start Payment Types
 ****/
export const GET_PAYMENT_TYPES = "GET_PAYMENT_TYPES";
export const ADD_NEW_PAYMENT_TYPE = "ADD_NEW_PAYMENT_TYPE";
export const REDIRECT_BACK_PAYMENT = "REDIRECT_BACK_PAYMENT";
export const GET_PAYMENTS_TYPE = "GET_PAYMENTS_TYPE";
export const DELETE_PAYMENTS_TYPE = "DELETE_PAYMENTS_TYPE";
export const TOGGLE_PAYMENTS_SINGLE_SELECT = "TOGGLE_PAYMENTS_SINGLE_SELECT";
export const TOOGLE_PAYMENTS_ALL_SELECT = "TOOGLE_PAYMENTS_ALL_SELECT";
export const UPDATE_PAYMENT_TYPE = "UPDATE_PAYMENT_TYPE";
export const UPDATE_ROW_DATA_PAYMENT_TYPE = "UPDATE_ROW_DATA_PAYMENT_TYPE";

/**
 *  End Payment Types
 * Start Loyalty
 ****/
export const GET_LOYALTY = "GET_LOYALTY";
export const ADD_NEW_LOYALTY = "ADD_NEW_LOYALTY";
/**
 * End Loyalty
 * Start Features
 ***/
export const GET_SETTING_FEATURES = "GET_SETTING_FEATURES";
export const UPDATE_SETTING_FEATURES = "UPDATE_SETTING_FEATURES";
export const TOGGLE_FEATURE_MODULE = "TOGGLE_FEATURE_MODULE";
/**
 * End Features
 * Start Receipt
 */
export const GET_RECEIPT = "GET_RECEIPT";
export const ADD_NEW_RECEIPT = "ADD_NEW_RECEIPT";
